### ISSUE TITLE
images from internet ---> Figma ----> aws studio ----> app🥸

### ISSUE THREAD

**Issue by Daveyd423** [CSNSE/app10#8]

**Comment by Daveyd423** [comment]
<img width="1470" alt="Screenshot 2024-01-23 at 7 50 37 AM" src="https://github.com/CSNSE/app10/assets/143111228/390cb2e6-502a-467e-bdf2-47b5b275828d">
You need to type copy the image address and paste it into the image source.

**Comment by Mr-Headrick** [comment]
This is what I want!
